# -- General configuration ------------------------------------------------
import os
import sys

import toml

# Add our custom extensions
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "_ext")))

# Read the current version from the pyproject.toml
package_version = toml.load("../pyproject.toml")["tool"]["poetry"]["version"]

# Add any Sphinx extension module names here, as strings.
extensions = [
    "djangodocs",
    "sphinx.ext.autodoc",
    "sphinx.ext.intersphinx",
    "sphinx.ext.viewcode",
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The suffix(es) of source filenames.
source_suffix = ".rst"

# The master toctree document.
master_doc = "index"

# General information about the project.
project = "django-allauth-webauthn"
copyright = "2021, H. Gregor Molter"
author = "H. Gregor Molter"

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = package_version
# The full version, including alpha/beta/rc tags.
release = package_version

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
language = None

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "sphinx"

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False


# -- Options for HTML output ----------------------------------------------
html_theme = "sphinx_rtd_theme"


# -- Options for HTMLHelp output ------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = "django-allauth-webauthn-doc"

# Example configuration for intersphinx: refer to the Python standard library.
intersphinx_mapping = {
    "python": ("https://docs.python.org/", None),
    "django": ("http://docs.djangoproject.com/en/dev/", "http://docs.djangoproject.com/en/dev/_objects/"),
}
