name: Publish (TestPyPI)

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
    - name: Build and publish
      run: |
        poetry version $(git describe --tags --abbrev=0)
        poetry build
        poetry config repositories.testpypi https://test.pypi.org/legacy/
        poetry publish --repository testpypi --username __token__ --password ${{ secrets.TEST_PYPI_TOKEN }}
